### ISSUE TITLE
add contact information

### ISSUE THREAD

**Issue by Bearwick** [isfit/App-isfit-25#13]
### Description
- Research if it is wanted to add contact information to e.g., head of ISFiT or HR.
- If so, add to information page

### Acceptance Criteria
- Research done
- Implemented if wanted

**Comment by da12345** [comment]
Contacted HR to find out which contact information they want listed on the app

**Comment by da12345** [comment]
HR still hasn't answered, so no progress can be made on this issue.

**Comment by da12345** [comment]
I am still in contact with HR to find out exactly what contact information to list.
